import React from 'react';
import ReactDOM from 'react-dom';
/*import ComponenteApp from './componente';
import ComponenteHora from './componenteHora';
import Contador from './componenteClicks';
import FCContador from './componenteClickHook';
import Tabla from './componenteTabla';*/
import Tablas from './componentesTodasTablas';
const num1 = 7;
const num2 = 8;
const divRoot = document.getElementById("root");
ReactDOM.render( <Tablas />, divRoot);